### ISSUE TITLE
Firefox 74 Enables Megabar by default

### ISSUE THREAD

**Issue by Excigma** [coekuss/quietfox#3]
![image](https://user-images.githubusercontent.com/30280397/74371786-4cb39d80-4e3e-11ea-8db9-681679105a1d.png)

**Comment by coekuss** [comment]
Thanks for showing this, I'll release an update when Firefox 74 comes to Stable. For now here is a quick fix:

Replace lines 505-508 with this: 
```css
#urlbar-background {
    background-color: transparent !important;
    border-color: transparent !important;
    box-shadow: none !important;
}

#urlbar[breakout][breakout-extend] {
    top: 4px !important;
    left: 0px !important;
    padding: 0px 0px 0px 0px !important;
    height: 100% !important;
    width: 100% !important;
}

#urlbar[breakout][breakout-extend] > #urlbar-input-container {
    height: var(--urlbar-toolbar-height) !important;
    padding-block: 0px !important;
    padding-inline: 0px !important;
    padding-bottom: 6px !important;
    margin-bottom: -5px !important;
    margin-top: -1px !important;
}

.urlbarView.megabar {
    width: 100% !important;
    margin-inline: 0px !important;
    box-shadow: 0px 5px 15px -7px black !important;
    border-radius: var(--menu-corner-rounding) !important;
    border: none !important;
}
```
